FROM node:20-alpine
ENV NODE_OPTIONS=--experimental-global-webcrypto
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build submission-service
EXPOSE 3003
CMD ["node", "dist/apps/submission-service/main"]

